project:
  type: book

execute: 
  freeze: auto

book:
  title: "大模型平台和应用实例"
  author: "gaoch"
  date: now
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - huggingface.qmd
    - huggingface-models.qmd
    - coze.qmd
    - bailian.qmd
    - volcengine.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    fig-width: 5.5
    fig-asp: 0.618
    warning: false
  pdf:
    documentclass: scrreprt
    fig-width: 5.5
    fig-asp: 0.618
    warning: false
    include-in-header: 
          text: |
            \usepackage{ctex}
            \usepackage{amsthm,mathrsfs}
            \usepackage{listings}
            \lstset{breaklines=true}