name: Publish Release with PDF

on:
  release:
    types: [created]

jobs:
  upload-release-asset:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Upload PDF to release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./pdf_book/大模型平台和应用实例.pdf  # 指定 book 目录下的 PDF 文件路径
        asset_name: 大模型平台和应用实例.pdf         # 发布时文件的名称
        asset_content_type: application/pdf   # 设置内容类型为 PDF
